'use client';
import { useEffect,useMemo,useState } from 'react';
import { capabilityForConfiguration,summarizeAnalyses,type AutomationAnalysis,type Capability } from '@/lib/automation-model';
import type { AutomationSettings } from '@/lib/automation-settings';
import { AutomationSetup } from './automation-setup';
import { AutomationRecipeEditor } from './automation-recipe-editor';

type Plan={id:number;name:string};
type Suite={id:number;name:string;suiteType?:string;requirementId?:number|null};
type Point={id:number;testCaseId:number;configurationId:number;configurationName:string;outcome:string;state:string};
type TestCase={id:number;title:string;order:number;azureState:string;description:string;steps:Array<{action:string;expected:string}>;points:Point[];active:boolean};
type Configuration={id:number;name:string;values?:unknown};
type Requirement={id:number;title:string;state:string;description:string;acceptanceCriteria:string};
type Details={suite:Suite|null;requirement:Requirement|null;testCases:TestCase[];points:Point[];configurations:Configuration[]};
type StoredAnalysis=AutomationAnalysis&{id?:number};
const labels:Record<string,string>={NOT_ANALYZED:'No analizado',ANALYZING:'Analizando',AUTOMATABLE:'Automatizable',PARTIALLY_AUTOMATABLE:'Parcialmente automatizable',NOT_AUTOMATABLE:'No automatizable',AUTOMATION_READY:'Listo para automatizar'};
async function json<T>(response:Response){const text=await response.text();let data:T&{error?:string};try{data=(text?JSON.parse(text):{})}catch{throw new Error(`Respuesta inválida (HTTP ${response.status}).`)}if(!response.ok)throw new Error(data.error??'No fue posible completar la consulta.');return data;}

export function AutomationPanel({project,plans,selectedPlanId,selectedSuiteId}:{project:string;plans:Plan[];suites:Suite[];selectedPlanId:number|null;selectedSuiteId:number|null}){
 const[planId,setPlanId]=useState<number|null>(selectedPlanId??plans[0]?.id??null);
 const[suiteId,setSuiteId]=useState<number|null>(selectedSuiteId),[suites,setSuites]=useState<Suite[]>([]);
 const[details,setDetails]=useState<Details|null>(null),[analyses,setAnalyses]=useState<StoredAnalysis[]>([]);
 const[selectedCaseId,setSelectedCaseId]=useState<number|null>(null),[settings,setSettings]=useState<AutomationSettings|null>(null);
 const[loading,setLoading]=useState(''),[error,setError]=useState(''),[preparing,setPreparing]=useState<number|'suite'|null>(null);
 useEffect(()=>{setPlanId(selectedPlanId??plans[0]?.id??null);setSuiteId(null);setSuites([]);setDetails(null);setAnalyses([]);setSelectedCaseId(null);setSettings(null);setError('');},[project,plans,selectedPlanId]);
 useEffect(()=>{if(!planId)return;const controller=new AbortController();setLoading('Cargando Test Suites requirement-based…');setSuites([]);setSuiteId(null);setDetails(null);fetch(`/api/azure/projects/${encodeURIComponent(project)}/plans/${planId}/suites`,{signal:controller.signal,cache:'no-store'}).then(json<{suites:Suite[]}>).then(data=>{const eligible=data.suites.filter(item=>item.requirementId||item.suiteType?.toLowerCase().includes('requirement'));setSuites(eligible);setSuiteId(eligible.find(item=>item.id===selectedSuiteId)?.id??eligible[0]?.id??null);setLoading('');}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading('');}});return()=>controller.abort();},[project,planId,selectedSuiteId]);
 useEffect(()=>{if(!planId||!suiteId)return;const controller=new AbortController();setLoading('Leyendo Test Cases, Test Points y configuraciones desde Azure…');setDetails(null);setAnalyses([]);setSelectedCaseId(null);Promise.all([fetch(`/api/azure/projects/${encodeURIComponent(project)}/plans/${planId}/suites/${suiteId}`,{signal:controller.signal,cache:'no-store'}).then(json<Details>),fetch(`/api/automation-analysis?project=${encodeURIComponent(project)}&planId=${planId}&suiteId=${suiteId}`,{signal:controller.signal,cache:'no-store'}).then(json<{analyses:StoredAnalysis[]}>)]).then(([suiteData,analysisData])=>{setDetails(suiteData);setAnalyses(analysisData.analyses);setLoading('');}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading('');}});return()=>controller.abort();},[project,planId,suiteId]);
 const activeCases=useMemo(()=>details?.testCases.filter(item=>item.active)??[],[details]);
 const byCase=useMemo(()=>new Map(analyses.map(item=>[item.testCaseId,item])),[analyses]);
 const configs=useMemo(()=>new Map((details?.configurations??[]).map(item=>[item.id,item])),[details]);
 const current=activeCases.find(item=>item.id===selectedCaseId)??null,summary=summarizeAnalyses(analyses.filter(item=>item.status!=='ANALYZING'));
 const capabilities=(testCase:TestCase):Capability[]=>[...new Map(testCase.points.map(point=>[point.configurationId,capabilityForConfiguration(configs.get(point.configurationId)??{id:point.configurationId,name:point.configurationName},settings?.configurationMappings[point.configurationName])])).values()];
 async function prepare(ids:number[]|undefined,marker:number|'suite'){if(!planId||!suiteId)return;setPreparing(marker);setError('');try{const data=await fetch('/api/automation-analysis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project,planId,suiteId,testCaseIds:ids})}).then(json<{analyses:StoredAnalysis[]}>);setAnalyses(previous=>{const map=new Map(previous.map(item=>[item.testCaseId,item]));data.analyses.forEach(item=>map.set(item.testCaseId,item));return[...map.values()];});}catch(e){setError(e instanceof Error?e.message:'No fue posible preparar la automatización.');}finally{setPreparing(null);}}
 return <div className="automation-page">
  <section className="automation-hero"><div><small>AZURE DEVOPS · WORKSPACE DE AUTOMATIZACIÓN</small><h2>Preparar automatización</h2><p>Convierte Test Cases reales en candidatos listos para implementación Playwright.</p></div><span>Proyecto <b>{project}</b></span></section>
  <AutomationSetup project={project} configurations={details?.configurations??[]} onSaved={setSettings}/>
  <section className="automation-context"><label>Test Plan<select value={planId??''} onChange={e=>setPlanId(Number(e.target.value)||null)}><option value="">Seleccionar…</option>{plans.map(item=><option key={item.id} value={item.id}>{item.id} · {item.name}</option>)}</select></label><label>Test Suite requirement-based<select value={suiteId??''} disabled={!suites.length} onChange={e=>setSuiteId(Number(e.target.value)||null)}><option value="">{suites.length?'Seleccionar…':'No hay suites requirement-based'}</option>{suites.map(item=><option key={item.id} value={item.id}>{item.id} · {item.name}</option>)}</select></label></section>
  {error&&<div className="automation-error">{error}</div>}{loading&&<div className="automation-loading"><i/>{loading}</div>}
  {!loading&&planId&&!suites.length&&<Empty title="Este Test Plan no tiene Test Suites requirement-based" text="Agrega suites asociadas a Historias de Usuario en Azure DevOps."/>}
  {!loading&&details&&<><section className="suite-overview"><div><small>SUITE SELECCIONADA</small><h3>{suiteId} · {suites.find(item=>item.id===suiteId)?.name}</h3><p>{details.requirement?`HU #${details.requirement.id} · ${details.requirement.title}`:'Sin HU asociada.'}</p></div><div className="suite-numbers"><b>{activeCases.length}<small>Test Cases activos</small></b><b>{activeCases.reduce((total,item)=>total+item.points.length,0)}<small>Test Points</small></b></div><button disabled={!activeCases.length||preparing!==null} onClick={()=>prepare(undefined,'suite')}>{preparing==='suite'?'Analizando…':'Preparar suite completa'}</button></section>
   {!!summary.analyzed&&<section className="analysis-summary"><article><b>{summary.analyzed}</b><span>Analizados</span></article><article className="good"><b>{summary.automatable}</b><span>Automatizables/listos</span></article><article className="warn"><b>{summary.partial}</b><span>Parciales</span></article><article className="bad"><b>{summary.notAutomatable}</b><span>No automatizables</span></article></section>}
   {!activeCases.length?<Empty title="La suite no tiene Test Cases vigentes" text="SGQA solo incorpora casos con Test Points vigentes en Azure."/>:<section className="automation-grid"><div className="case-worklist"><header><div><small>CASOS VIGENTES EN AZURE</small><h3>{activeCases.length} casos para preparar</h3></div></header>{activeCases.map(testCase=><CaseCard key={testCase.id} testCase={testCase} analysis={byCase.get(testCase.id)} capabilities={capabilities(testCase)} selected={selectedCaseId===testCase.id} busy={preparing!==null} onSelect={()=>setSelectedCaseId(testCase.id)} onPrepare={()=>prepare([testCase.id],testCase.id)}/>)}</div><aside className="case-inspector">{current&&planId&&suiteId?<Inspector project={project} planId={planId} suiteId={suiteId} testCase={current} requirement={details.requirement} analysis={byCase.get(current.id)} capabilities={capabilities(current)}/>:<Empty title="Selecciona un Test Case" text="Aquí verás los pasos, capacidades y contexto faltante."/>}</aside></section>}
  </>}
 </div>;
}

function CaseCard({testCase,analysis,capabilities,selected,busy,onSelect,onPrepare}:{testCase:TestCase;analysis?:StoredAnalysis;capabilities:Capability[];selected:boolean;busy:boolean;onSelect:()=>void;onPrepare:()=>void}){const caps=analysis?.capabilities.length?analysis.capabilities:capabilities;return <article className={selected?'selected':''} onClick={onSelect}><div className="case-top"><span className="azure-state">Azure · {testCase.azureState||'Vigente'}</span><span className={`analysis-state ${analysis?.status??'NOT_ANALYZED'}`}>{labels[analysis?.status??'NOT_ANALYZED']}</span></div><h4>#{testCase.id} · {testCase.title}</h4><p>{testCase.steps.length} pasos · {testCase.points.length} Test Points</p><div className="capability-list">{caps.map(cap=><span key={cap.configurationId} className={cap.state}>{cap.configurationName} · {cap.state.replace('_',' ')}</span>)}</div><footer><button onClick={event=>{event.stopPropagation();onSelect();}}>Ver detalle</button><button className="primary" disabled={busy} onClick={event=>{event.stopPropagation();onPrepare();}}>Preparar automatización</button></footer></article>;}
function Inspector({project,planId,suiteId,testCase,requirement,analysis,capabilities}:{project:string;planId:number;suiteId:number;testCase:TestCase;requirement:Requirement|null;analysis?:StoredAnalysis;capabilities:Capability[]}){const caps=analysis?.capabilities.length?analysis.capabilities:capabilities;return <div className="inspector-content"><small>DETALLE DEL TEST CASE</small><h3>#{testCase.id} · {testCase.title}</h3><section><b>Historia de Usuario</b><p>{requirement?`#${requirement.id} · ${requirement.title}`:'Sin HU resoluble.'}</p></section><section><b>Pasos manuales en Azure</b>{testCase.steps.length?<ol>{testCase.steps.map((step,index)=><li key={index}><strong>{step.action}</strong><span>Esperado: {step.expected||'No especificado'}</span></li>)}</ol>:<p className="muted">Sin pasos manuales.</p>}</section><section><b>Capacidad por configuración</b>{caps.map(cap=><div className="capability-detail" key={cap.configurationId}><span className={cap.state}>{cap.state}</span><div><strong>{cap.configurationName} · {cap.engine}</strong><p>{cap.note}</p></div></div>)}</section><section><b>Análisis</b>{analysis?<><span className={`analysis-state ${analysis.status}`}>{labels[analysis.status]}</span><p>{analysis.reason}</p><p><strong>Confianza:</strong> {Math.round(analysis.confidence*100)}%</p>{analysis.missingContext.length>0&&<div className="missing-context"><b>Contexto faltante</b>{analysis.missingContext.map(item=><span key={item}>{item}</span>)}</div>}</>:<p className="muted">Aún no analizado.</p>}<AutomationRecipeEditor key={`${project}:${planId}:${suiteId}:${testCase.id}`} project={project} planId={planId} suiteId={suiteId} testCase={testCase} automationReady={analysis?.status==='AUTOMATION_READY'}/></section></div>;}
function Empty({title,text}:{title:string;text:string}){return <div className="automation-empty"><div>⌘</div><b>{title}</b><p>{text}</p></div>;}
