'use client';
import { useEffect,useMemo,useState } from 'react';
import type { AutomationRecipe,RecipeOperation,ActionType,AssertionType } from '@/lib/automation-recipe';
type TestCase={id:number;title:string;steps:Array<{action:string;expected:string}>;points?:Array<{configurationId:number;configurationName:string}>};
type ExecutionConfiguration={name:string;engine:string;state:string};
type Artifact={id:number;fileName:string};
type RunnerEvidence={name:string;kind:'video'|'screenshot'|'trace'};
type RunnerRun={id:string;status:'running'|'passed'|'failed'|'blocked'|'sync_failed';outcome?:string;azureRunId?:number;azureUrl?:string;output:string;evidence:RunnerEvidence[]};
const runnerUrl='http://127.0.0.1:3101';
const newOperation=(testCase:TestCase,index:number):RecipeOperation=>({id:crypto.randomUUID(),azureStepIndex:index,label:testCase.steps[index]?.action||`Paso ${index+1}`,action:'click',locator:'',valueSource:'literal',value:'',assertion:'visible',assertionLocator:'',expected:testCase.steps[index]?.expected||''});
async function json<T>(response:Response){const data=await response.json() as T&{error?:string};if(!response.ok)throw new Error(data.error??'No fue posible completar la acción.');return data;}
function runnerFor(engine:string){const value=engine.toLowerCase();if(value.includes('firefox'))return'firefox';if(value.includes('edge'))return'edge';if(value.includes('webkit')||value.includes('safari'))return'webkit';if(value.includes('device')||value.includes('responsive')||value.includes('android')||value.includes('ios'))return'mobile-web';return'chromium';}

export function AutomationRecipeEditor({project,planId,suiteId,testCase,automationReady,configurations}:{project:string;planId:number;suiteId:number;testCase:TestCase;automationReady:boolean;configurations?:ExecutionConfiguration[]}){
 const[recipe,setRecipe]=useState<AutomationRecipe|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[artifact,setArtifact]=useState<Artifact|null>(null),[run,setRun]=useState<RunnerRun|null>(null),[runnerOnline,setRunnerOnline]=useState(false);
 const executable=useMemo(()=>configurations?.filter(item=>['SUPPORTED','EMULATED'].includes(item.state))??[...new Map((testCase.points??[]).map(item=>[item.configurationName,{name:item.configurationName,engine:item.configurationName,state:'SUPPORTED'}])).values()],[configurations,testCase.points]);
 const[configuration,setConfiguration]=useState(executable[0]?.name??'');
 useEffect(()=>{const controller=new AbortController();fetch(`/api/automation-recipes?project=${encodeURIComponent(project)}&planId=${planId}&suiteId=${suiteId}&testCaseId=${testCase.id}`,{signal:controller.signal,cache:'no-store'}).then(json<{recipe:AutomationRecipe}>).then(data=>setRecipe(data.recipe)).catch(error=>{if(error.name!=='AbortError')setMessage(error.message)});fetch(`${runnerUrl}/health`,{signal:controller.signal}).then(response=>setRunnerOnline(response.ok)).catch(()=>setRunnerOnline(false));return()=>controller.abort();},[project,planId,suiteId,testCase.id]);
 useEffect(()=>{if(!run||run.status!=='running')return;const timer=setInterval(()=>fetch(`${runnerUrl}/runs`).then(json<{runs:RunnerRun[]}>).then(data=>{const updated=data.runs.find(item=>item.id===run.id);if(updated)setRun(updated);}).catch(()=>undefined),1500);return()=>clearInterval(timer);},[run]);
 function update(id:string,patch:Partial<RecipeOperation>){setRecipe(current=>current?{...current,operations:current.operations.map(item=>item.id===id?{...item,...patch}:item),status:'DRAFT'}:current);}
 function add(stepIndex:number){setRecipe(current=>current?{...current,operations:[...current.operations,newOperation(testCase,stepIndex)],status:'DRAFT'}:current);}
 function remove(id:string){setRecipe(current=>current?{...current,operations:current.operations.filter(item=>item.id!==id),status:'DRAFT'}:current);}
 async function save(){if(!recipe)return;setBusy(true);setMessage('');try{const data=await fetch('/api/automation-recipes',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(recipe)}).then(json<{recipe:AutomationRecipe;errors:string[]}>);setRecipe(data.recipe);setMessage(data.errors.length?data.errors.join(' '):'Receta validada y lista para generar.');}catch(error){setMessage(error instanceof Error?error.message:'No fue posible guardar.')}finally{setBusy(false)}}
 async function generate(){if(!recipe)return;setBusy(true);setMessage('');try{const data=await fetch('/api/automation-artifacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project,planId,suiteId,testCaseId:testCase.id})}).then(json<{artifact:Artifact}>);setArtifact(data.artifact);setMessage('Playwright generado sin TODO ni test.fixme.');}catch(error){setMessage(error instanceof Error?error.message:'No fue posible generar.')}finally{setBusy(false)}}
 async function execute(){if(!artifact||!configuration)return;setBusy(true);setMessage('');try{const source=await fetch(`/api/automation-artifacts?id=${artifact.id}`).then(async response=>{if(!response.ok)throw new Error('No fue posible recuperar el Playwright generado.');return response.text()});const selected=executable.find(item=>item.name===configuration);const data=await fetch(`${runnerUrl}/recipe-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project,planId,suiteId,testCaseId:testCase.id,testCaseTitle:testCase.title,configurationName:configuration,runner:runnerFor(selected?.engine??''),source,steps:testCase.steps})}).then(json<{run:RunnerRun}>);setRun(data.run);setMessage('Ejecución iniciada. El resultado y las evidencias se publicarán automáticamente en Azure DevOps.');}catch(error){setMessage(error instanceof Error?error.message:'No fue posible iniciar la ejecución local.')}finally{setBusy(false)}}
 if(!recipe)return <div className="recipe-loading">Cargando receta…</div>;
 return <div className="recipe-editor"><header><div><b>Receta ejecutable</b><span className={recipe.status}>{recipe.status==='READY'?'Lista':'Pendiente'}</span></div><button onClick={()=>setOpen(value=>!value)}>{open?'Cerrar editor':'Configurar pasos'}</button></header>{message&&<p className="recipe-message">{message}</p>}{open&&<div className="recipe-body">{testCase.steps.map((manualStep,stepIndex)=><section key={stepIndex}><div className="manual-step"><b>Paso Azure {stepIndex+1}</b><p>{manualStep.action}</p><small>Esperado: {manualStep.expected||'No especificado'}</small></div>{recipe.operations.filter(item=>item.azureStepIndex===stepIndex).map((operation,index)=><OperationRow key={operation.id} operation={operation} number={index+1} update={patch=>update(operation.id,patch)} remove={()=>remove(operation.id)}/>) }<button className="add-operation" onClick={()=>add(stepIndex)}>+ Añadir acción</button></section>)}<footer><span>Los locators deben estar confirmados en el aplicativo.</span><button disabled={busy} onClick={save}>{busy?'Guardando…':'Guardar y validar receta'}</button></footer></div>}<div className="recipe-generate"><button disabled={busy||recipe.status!=='READY'||!automationReady} onClick={generate}>Generar Playwright</button>{!automationReady&&<small>Primero prepara el caso hasta AUTOMATION_READY.</small>}{artifact&&<a href={`/api/automation-artifacts?id=${artifact.id}`}>Descargar {artifact.fileName}</a>}</div>{artifact&&<div className="recipe-execution"><div className="runner-state"><i className={runnerOnline?'online':'offline'}/>{runnerOnline?'Runner local conectado':'Runner local desconectado'}</div><label>Configuración Azure<select value={configuration} onChange={event=>setConfiguration(event.target.value)}><option value="">Seleccionar…</option>{executable.map(item=><option key={item.name} value={item.name}>{item.name} · {item.engine}</option>)}</select></label><button disabled={busy||!runnerOnline||!configuration||run?.status==='running'} onClick={execute}>{run?.status==='running'?'Ejecutando…':'Ejecutar y publicar en Azure'}</button></div>}{run&&<RunResult run={run}/>}</div>;
}

function RunResult({run}:{run:RunnerRun}){return <div className={`recipe-run ${run.status}`}><header><b>{run.status==='running'?'Ejecución en curso':`Resultado: ${run.outcome??run.status}`}</b>{run.azureUrl&&<a href={run.azureUrl} target="_blank" rel="noreferrer">Abrir Test Run #{run.azureRunId}</a>}</header>{run.evidence.length>0&&<div className="run-evidence">{run.evidence.map((item,index)=><a key={`${item.name}-${index}`} href={`${runnerUrl}/runs/${run.id}/evidence/${index}`} target="_blank" rel="noreferrer">{item.kind==='video'?'▶':item.kind==='screenshot'?'▧':'⌁'} {item.name}</a>)}</div>}{run.status==='sync_failed'&&<p>La prueba terminó, pero Azure DevOps rechazó la publicación. Revisa el detalle técnico.</p>}{run.status!=='running'&&run.output&&<details><summary>Detalle técnico</summary><pre>{run.output}</pre></details>}</div>}
function OperationRow({operation,number,update,remove}:{operation:RecipeOperation;number:number;update:(patch:Partial<RecipeOperation>)=>void;remove:()=>void}){const needsValue=['goto','fill','select','press'].includes(operation.action);return <div className="operation-row"><div className="operation-title"><b>Acción {number}</b><button onClick={remove}>Eliminar</button></div><label>Acción<select value={operation.action} onChange={e=>update({action:e.target.value as ActionType})}><option value="goto">Navegar</option><option value="click">Clic</option><option value="fill">Completar campo</option><option value="select">Seleccionar opción</option><option value="check">Marcar</option><option value="press">Presionar tecla</option></select></label>{operation.action!=='goto'&&<label>Locator confirmado<input value={operation.locator} onChange={e=>update({locator:e.target.value})} placeholder="role=button[name=Continuar]"/></label>}{needsValue&&<><label>Origen del valor<select value={operation.valueSource} onChange={e=>update({valueSource:e.target.value as 'literal'|'env'})}><option value="literal">Dato literal</option><option value="env">Variable de entorno</option></select></label><label>{operation.valueSource==='env'?'Nombre de variable':'Valor'}<input value={operation.value} onChange={e=>update({value:e.target.value})} placeholder={operation.valueSource==='env'?'QA_TEST_VALUE':'/dashboard'}/></label></>}<label>Validación<select value={operation.assertion} onChange={e=>update({assertion:e.target.value as AssertionType})}><option value="none">Sin validación</option><option value="visible">Elemento visible</option><option value="hidden">Elemento oculto</option><option value="text">Contiene texto</option><option value="url">URL coincide</option></select></label>{!['none','url'].includes(operation.assertion)&&<label>Locator de validación<input value={operation.assertionLocator} onChange={e=>update({assertionLocator:e.target.value})} placeholder="Vacío = usar locator de acción"/></label>}{['text','url'].includes(operation.assertion)&&<label>Resultado esperado<input value={operation.expected} onChange={e=>update({expected:e.target.value})}/></label>}</div>}
