"use client";
import { FormEvent, useState } from "react";
type Plan={id:number;name:string;state:string;areaPath:string;iteration:string;startDate:string;endDate:string;rootSuiteId:number|null};
type Requirement={id:number;title:string;iteration:string;description?:string;acceptanceCriteria?:string};
type Props={project:string;plans:Plan[];selectedRequirements:Requirement[];selectedPlanId:number|null;onClose:()=>void;onPlanCreated:(plan:Plan)=>void;onContinue:(planId:number)=>void};
export function DesignPreparationModal({project,plans,selectedRequirements,selectedPlanId,onClose,onPlanCreated,onContinue}:Props){
 const[destination,setDestination]=useState<number|null>(selectedPlanId??plans[0]?.id??null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[duplicate,setDuplicate]=useState<Plan|null>(null);
 const iterations=[...new Set(selectedRequirements.map(item=>item.iteration).filter(Boolean))],iteration=iterations[0]??"";
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setDuplicate(null);const form=new FormData(event.currentTarget),name=String(form.get("name")??"").trim(),description=String(form.get("description")??"").trim();try{const response=await fetch(`/api/azure/projects/${encodeURIComponent(project)}/plans`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,description,iteration})}),text=await response.text(),data=(text?JSON.parse(text):{}) as {plan?:Plan;existingPlan?:Plan;error?:string};if(response.status===409&&data.existingPlan){setDuplicate(data.existingPlan);setError(`Ya existe “${data.existingPlan.name}”. Puedes utilizar el Test Plan existente.`);return}if(!response.ok||!data.plan)throw new Error(data.error??"No fue posible crear el Test Plan.");onPlanCreated(data.plan);setDestination(data.plan.id);setCreating(false)}catch(value){setError(value instanceof Error?value.message:"No fue posible crear el Test Plan.")}finally{setBusy(false)}}
 async function continueToDesign(){if(!destination)return;setBusy(true);setError("");try{const response=await fetch("/api/test-designs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project,requirements:selectedRequirements})}),text=await response.text(),data=(text?JSON.parse(text):{}) as {error?:string};if(!response.ok)throw new Error(data.error??"No fue posible preparar el diseño de pruebas.");onContinue(destination)}catch(value){setError(value instanceof Error?value.message:"No fue posible preparar el diseño de pruebas.")}finally{setBusy(false)}}
 return <div className="prep-backdrop" role="dialog" aria-modal="true" aria-label="Preparar diseño de pruebas"><section className="prep-modal"><header><div><small>{creating?"AZURE DEVOPS":"DESTINO DE PUBLICACIÓN"}</small><h2>{creating?"Crear Test Plan":"Preparar diseño de pruebas"}</h2></div><button aria-label="Cerrar" onClick={onClose}>×</button></header>{creating?<form onSubmit={create}><label>Proyecto<strong>{project}</strong></label><label>Nombre<input name="name" required autoFocus placeholder="QA - SPRINT 05"/></label><label>Descripción (opcional)<textarea name="description" placeholder="Pruebas funcionales Sprint 05"/></label><p className="prep-context">Iteración: <b>{iteration||"No disponible"}</b> · Área automática: <b>{project}\\QA</b></p>{iterations.length>1&&<p className="prep-warning">Las HUs pertenecen a varias iteraciones. El plan se creará para {iteration}.</p>}{error&&<div className="prep-error">⚠ {error}{duplicate&&<button type="button" onClick={()=>{setDestination(duplicate.id);setCreating(false);setError("");setDuplicate(null)}}>Seleccionar existente</button>}</div>}<footer><button type="button" className="secondary" onClick={()=>{setCreating(false);setError("")}}>Cancelar</button><button disabled={busy||!iteration}>{busy?"Creando…":"Crear Test Plan"}</button></footer></form>:<div className="prep-select"><p>Has seleccionado <b>{selectedRequirements.length} historias de usuario</b>.</p><label>Proyecto<strong>{project}</strong></label><label>Test Plan destino<select value={destination??""} onChange={event=>setDestination(Number(event.target.value))}><option value="" disabled>Seleccionar Test Plan…</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.id} · {plan.name}</option>)}</select></label><div className="prep-create"><span>¿No existe el Test Plan que necesitas?</span><button onClick={()=>setCreating(true)}>＋ Crear nuevo Test Plan</button></div>{error&&<div className="prep-error">⚠ {error}</div>}<footer><button className="secondary" onClick={onClose}>Cancelar</button><button disabled={!destination||busy} onClick={continueToDesign}>{busy?"Generando diseño…":"Continuar →"}</button></footer></div>}</section></div>;
}
