'use client';
import { FormEvent, useEffect, useState } from 'react';
import { extractRfc } from '@/lib/extract-rfc';
type Requirement={id:number;parentId:number|null;title:string;type:string;attachments:{id:string;name:string;comment:string}[]};
type Rfc={id:number;name:string;originalFileName:string;mimeType:string;size:number;version:string;status:string;extractedText:string;huIds:number[];createdAt:string};
const readRfcs=(response:Response)=>response.json() as Promise<{rfcs:Rfc[]}>;
export function RfcPanel({project,selectedHuIds,requirements,onContinue}:{project:string;selectedHuIds:number[];requirements:Requirement[];onContinue:()=>void}){
 const[rfcs,setRfcs]=useState<Rfc[]>([]),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[preview,setPreview]=useState<Rfc|null>(null);
 useEffect(()=>{fetch(`/api/rfcs?project=${encodeURIComponent(project)}`).then(readRfcs).then(data=>setRfcs(data.rfcs??[]));},[project]);
 const relatedIds=new Set(selectedHuIds.length?selectedHuIds:requirements.map(item=>item.id));let pending=[...selectedHuIds];
 while(pending.length){const item=requirements.find(r=>r.id===pending.pop());if(item?.parentId&&!relatedIds.has(item.parentId)){relatedIds.add(item.parentId);pending.push(item.parentId);}}
 const azureAttachments=requirements.filter(item=>relatedIds.has(item.id)).flatMap(item=>item.attachments.map(file=>({...file,workItemId:item.id,workItemTitle:item.title}))).filter((file,index,all)=>all.findIndex(item=>item.id===file.id)===index);
 async function refresh(){const data=await fetch(`/api/rfcs?project=${encodeURIComponent(project)}`).then(readRfcs);setRfcs(data.rfcs??[]);}
 async function processFile(file:File,name:string,version:string){setUploading(true);setMessage('Extrayendo contenido localmente…');try{const extractedText=await extractRfc(file);if(!extractedText)throw new Error('No se pudo extraer texto del documento.');const response=await fetch('/api/rfcs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project,name,version,originalFileName:file.name,mimeType:file.type||'application/octet-stream',size:file.size,extractedText,huIds:selectedHuIds})});const responseText=await response.text();let result:{error?:string}={};if(responseText){try{result=JSON.parse(responseText) as {error?:string};}catch{if(!response.ok)throw new Error(`No fue posible guardar el RFC (HTTP ${response.status}).`);}}if(!response.ok)throw new Error(result.error??`No fue posible guardar el RFC (HTTP ${response.status}).`);await refresh();setMessage(`RFC guardado correctamente como versión ${version}.`);}catch(error){setMessage(error instanceof Error?error.message:'Error procesando el RFC.');}finally{setUploading(false);}}
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),file=form.get('file') as File,name=String(form.get('name')??'').trim(),version=String(form.get('version')??'1.0').trim();if(!file?.size||!name)return;await processFile(file,name,version);event.currentTarget.reset();}
 async function importAttachment(file:{id:string;name:string}){setUploading(true);setMessage(`Descargando ${file.name} desde Azure DevOps…`);try{const response=await fetch(`/api/azure/projects/${encodeURIComponent(project)}/attachments/${file.id}`);if(!response.ok)throw new Error('No fue posible descargar el adjunto desde Azure DevOps.');const blob=await response.blob();await processFile(new File([blob],file.name,{type:blob.type}),file.name.replace(/\.[^.]+$/,''),'1.0');}catch(error){setMessage(error instanceof Error?error.message:'Error importando el adjunto.');setUploading(false);}}
 return <div className="rfc-page">
  <section className="azure-attachments"><div className="panel-title"><div><small>ORIGEN PRINCIPAL · AZURE DEVOPS</small><h3>{selectedHuIds.length?'Adjuntos relacionados con las HUs seleccionadas':'Todos los adjuntos de requisitos del proyecto'}</h3></div><span>{azureAttachments.length} archivos</span></div>
   {azureAttachments.length?<div className="attachment-list">{azureAttachments.map(file=><article key={file.id}><span className="file-icon">{file.name.split('.').pop()?.toUpperCase()}</span><div><b>{file.name}</b><small>Work Item {file.workItemId} · {file.workItemTitle}</small>{file.comment&&<p>{file.comment}</p>}</div><div className="attachment-actions"><a href={`/api/azure/projects/${encodeURIComponent(project)}/attachments/${file.id}?name=${encodeURIComponent(file.name)}`} download={file.name}>↓ Descargar</a><button disabled={uploading} onClick={()=>importAttachment(file)}>Importar RFC</button></div></article>)}</div>:<div className="empty">No se encontraron adjuntos en Epic, Features o HUs del proyecto.</div>}
  </section>
  <section className="rfc-upload"><div><small>CARGA MANUAL · RESPALDO</small><h2>Agregar otro RFC</h2><p>Úsalo solamente cuando el documento todavía no esté adjunto en Azure DevOps.</p></div><form onSubmit={upload}><label>Nombre del RFC<input name="name" required placeholder="Ej. RFC Perfilamiento Fase 2"/></label><label>Versión<input name="version" required defaultValue="1.0"/></label><label className="file-field">Archivo<input name="file" type="file" accept=".pdf,.docx,.txt,.md" required/><span>PDF, DOCX, TXT o MD · Máximo 8 MB</span></label><div className="hu-association"><b>{selectedHuIds.length} HUs asociadas</b><span>{selectedHuIds.length?selectedHuIds.map(id=>`#${id}`).join(', '):'Sin filtro: se muestran todos los adjuntos del proyecto.'}</span></div><button disabled={uploading}>{uploading?'Procesando…':'Subir y procesar RFC'}</button>{message&&<p className="upload-message">{message}</p>}</form></section>
  <section className="rfc-library"><div className="panel-title"><div><small>BIBLIOTECA DEL PROYECTO</small><h3>RFC registrados</h3></div><span>{rfcs.length} documentos</span></div>{rfcs.length?<div className="rfc-list">{rfcs.map(rfc=><article key={rfc.id} className={preview?.id===rfc.id?'selected':''} onClick={()=>setPreview(rfc)}><span className="file-icon">{rfc.originalFileName.split('.').pop()?.toUpperCase()}</span><div><b>{rfc.name}</b><small>{rfc.originalFileName} · {(rfc.size/1024).toFixed(0)} KB</small><p>Versión {rfc.version} · {rfc.huIds.length} HUs asociadas</p></div><em>{rfc.status}</em></article>)}</div>:<div className="empty">Aún no existen RFC importados para {project}.</div>}</section>
  {preview&&<aside className="rfc-preview"><div><small>VISTA PREVIA EXTRAÍDA</small><h3>{preview.name} · v{preview.version}</h3></div><pre>{preview.extractedText.slice(0,12000)}</pre><div className="preview-actions"><button onClick={()=>setPreview(null)} className="secondary">Cerrar</button><button onClick={onContinue}>Usar para diseñar casos →</button></div></aside>}
 </div>;
}
